### ISSUE TITLE
Peer dependency issue

### ISSUE THREAD

**Issue by wrousseau** [knowbody/react-native-platform-stylesheet#3]
Hi there,

Cool stuff, thanks ! However, the peer dependency is causing issues for me (your module works fine for higher version of react native actually). Could you patch it for it not to cause warnings or errors for higher versions of react native ?

Thanks a lot,

**Comment by knowbody** [comment]
@wrousseau thanks for pointing it out, mind sending PR? and I will cut the release after that

**Comment by wrousseau** [comment]
Sure, here it is ! https://github.com/knowbody/react-native-platform-stylesheet/pull/4

Thanks a lot :)

**Comment by wrousseau** [comment]
@knowbody If you can make a new release today it would be awesome :)

**Comment by knowbody** [comment]
done! Thanks for the PR again!
